import { useState } from "react";

export default function FAQ() {
  const [openIdx, setOpenIdx] = useState(null);

  const faqs = [
    {
      q: "How does the AI resume builder work?",
      a: "Simply describe your experience, skills, and achievements in plain English. Our AI analyzes your input and generates a professional, ATS-optimized resume tailored to your industry and career level."
    },
    {
      q: "Will my resume pass ATS screening?",
      a: "Yes! Every resume generated by Prompt Resume is optimized for Applicant Tracking Systems. We analyze keywords, formatting, and structure to ensure maximum compatibility with ATS software."
    },
    {
      q: "Can I edit the generated resume?",
      a: "Absolutely. You have full control over every section. Edit text, reorder sections, change templates, or adjust formatting. The AI gives you a strong starting point that you can customize."
    },
    {
      q: "What templates are available?",
      a: "We offer 15+ professional templates across industries including tech, finance, healthcare, and creative fields. Each template is designed for both human readers and ATS systems."
    },
    {
      q: "Is there a free plan?",
      a: "Yes! Our Starter plan includes 1 resume generation, basic templates, and PDF export. No credit card required to get started."
    },
    {
      q: "Can I create cover letters too?",
      a: "Yes, our Pro plan includes AI-powered cover letter generation. Simply provide the job description and your experience, and we'll create a tailored cover letter."
    }
  ];

  return (
    <section className="faq-section" id="faq">
      <div className="faq-inner">
        <div className="reveal">
          <div className="section-tag">FAQ</div>
          <h2 className="section-headline">Frequently asked questions</h2>
          <p className="section-sub">Everything you need to know about Prompt Resume.</p>
        </div>

        <div className="faq-list reveal">
          {faqs.map((faq, i) => (
            <div key={i} className="faq-item">
              <button
                className="faq-question"
                onClick={() => setOpenIdx(openIdx === i ? null : i)}
              >
                {faq.q}
                <span className={`faq-icon ${openIdx === i ? 'open' : ''}`}>+</span>
              </button>
              <div className={`faq-answer ${openIdx === i ? 'open' : ''}`}>
                {faq.a}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
